### ISSUE TITLE
Connection timed out error

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/TSDB-migration-test-kit#5]
At the time of copping documents to tsdb index, I am getting this error:
```
Copying documents from .ds-metrics-prometheus.collector-default-2023.08.04-000001 to tsdb-index-enabled...
Traceback (most recent call last):
  File "/Users/tetianakravchenko/git/TSDB-migration-test-kit/main.py", line 172, in <module>
    all_placed = copy_from_data_stream(client, args.data_stream, int(args.docs_index), int(args.settings_mappings_index),
  File "/Users/tetianakravchenko/git/TSDB-migration-test-kit/utils/es.py", line 333, in copy_from_data_stream
    return copy_docs_from_to(client, source_index, tsdb_index, max_docs)
  File "/Users/tetianakravchenko/git/TSDB-migration-test-kit/utils/es.py", line 252, in copy_docs_from_to
    resp = client.reindex(source={"index": source_index}, dest={"index": dest_index}, refresh=True)
  File "/Users/tetianakravchenko/git/TSDB-migration-test-kit/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/Users/tetianakravchenko/git/TSDB-migration-test-kit/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py", line 3226, in reindex
    return self.perform_request(  # type: ignore[return-value]
  File "/Users/tetianakravchenko/git/TSDB-migration-test-kit/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 285, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/Users/tetianakravchenko/git/TSDB-migration-test-kit/.venv/lib/python3.10/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/Users/tetianakravchenko/git/TSDB-migration-test-kit/.venv/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionTimeout: Connection timed out
```

Some how I think it could be related to the size/docs number of the index:
<img width="1923" alt="Screenshot 2023-08-04 at 16 28 07" src="https://github.com/elastic/TSDB-migration-test-kit/assets/28299531/61e7c4a0-40e6-4400-8370-b7e47648f98d">

for the `metrics-prometheus.collector-default` I see this error, but for `metrics-prometheus.query-default` all works fine.

**Comment by constanca-m** [comment]
I updated the README file to include this error. I will close this issue now.
